### ISSUE TITLE
Atomic Polarizability seemingly calculating extra transitions that don't exist

### ISSUE THREAD

**Issue by deejaybee11** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#60] opened 2021-03-26 01:01 UTC
When calculating the dynamic polarizability of Caesium and Rubidium using getPolarizability I am getting results that don't seem correct. 

For the ground state of Rubidium 5s1/2 ,I get the usual asymptotes at 780 and 795 nm but another occurs at around 1100 nm which does not correspond to any real transition in Rubidium. 

Likewise with Caesium I am using it to calculate the polarizability of Rydberg states following the idea of J. Phys. B: At. Mol. Opt. Phys. 53 (2020) 155302, however the results I obtain have an additional asymptote occurring at around 1350 nm, where as the authors in the previous article do not get anything showing up at this point. 

Is this something you could please explain to me?

**Comment by deejaybee11** [comment] 2021-03-26 02:22
![Figure_1](https://user-images.githubusercontent.com/11435053/112568064-3f305b80-8e25-11eb-8d26-d65f27c4257f.png)
As an example, this figure shows the polarizability of the ground state of Rb87 in red (5s1/2) and a rydberg state in blue as a function of wavelength. The lack of detail on the blue asymptotes is purely due to the lack of points in the calculation. 

As you can see the ground state has a distinct feature around 1000 nm, which doesn't correspond to any real transitions of Rubidium.

**Comment by nikolasibalic** [comment] 2021-03-26 08:27
Thank you for you message @deejaybee11 

Could you please share your code, as I cannot reproduce this issue?
Also please ensure that you have latest ARC version (3.0.11).

This is what I get with a test code:
```python
from arc import *

atom = Rubidium87()
n = 23
calc = DynamicPolarizability(atom, n, 1, 0.5)
calc.defineBasis(atom.groundStateN, n+15)
calc.getPolarizability(1100e-9,units="a.u.")

calcGroundState = DynamicPolarizability(atom, 5, 0, 0.5)
calcGroundState.defineBasis(atom.groundStateN, 25)

wavelengthList = np.linspace(600, 1400,1000) * 1e-9  # m
print("now rydberg state")
ax = calc.plotPolarizability(wavelengthList, debugOutput=True, units="au")
print("now ground state")
calcGroundState.plotPolarizability(wavelengthList, debugOutput=True, units="au", addToPlotAxis=ax, line="r--")

import matplotlib.lines as mlines

ax.set_ylim(-4000,4000)

plt.legend(handles=[mlines.Line2D([], [], color="b", linestyle="-",
                          label=(r'$\alpha[%s]$' % printStateStringLatex(n,1,0.5))),
            mlines.Line2D([], [], color='r', linestyle='--',
                          label=(r'$\alpha[%s]$' % printStateStringLatex(5,0,0.5)))],
          loc='lower right')
plt.show()
```
```
now rydberg state
now ground state
Resonance: 780.98 nm 5 2P 3/2
Resonance: 795.40 nm 5 2P 1/2
```
![test](https://user-images.githubusercontent.com/24477754/112603477-5b2c0100-8e15-11eb-9727-b41d35003a09.png)

**Comment by deejaybee11** [comment] 2021-03-27 06:56
Thank you very much for such a quick response. My code is a bit messy, hopefully it is understandable enough. I realize I may be including too many states in the ground state basis when compared to your snippet there. I forgot to note my code includes the tensor polarizability but I don't see that causing the issue.

`
atom = arc.Rubidium()
npts = 1000
lmbda = np.linspace(600e-9, 1600e-9, npts)
groundState = arc.DynamicPolarizability(atom, 5, 0, 0.5)
groundState.defineBasis(1, 70)

for i in range(nmin, nmax):
    
    excitedState = arc.DynamicPolarizability(atom, i, 0, 0.5)
      excitedState.defineBasis(1, 80)
    
    z = []
    z2 = []
    for j in range(0, len(lmbda)):
        
        if (i==0):
            z.append(groundState.getPolarizability(lmbda[j], mj=1/2, accountForStateLifetime=True, units='au'))
        z2.append(excitedState.getPolarizability(lmbda[j], mj=1/2, accountForStateLifetime=True, units='au'))


gnd = np.load("ground.npy", allow_pickle=True)
for i in range(nmin,nmax):
    
    plt.figure()
    exc = np.load(str(i)+"exc.npy", allow_pickle=True)
    plt.plot(lmbda, gnd[:,0]+gnd[:,2], 'r--')
    plt.plot(lmbda, exc[:,0]+exc[:,2], 'b-')
    plt.ylim(-4000,4000)

`

Results in the following plot
![image](https://user-images.githubusercontent.com/11435053/112712662-42564500-8f14-11eb-9521-dc248b8c984f.png)


Thank you very much again.

**Comment by deejaybee11** [comment] 2021-03-29 04:07
It appears I made a mistake with the lowest basis level of the ground state. Having the basis start at n=1 caused this extra feature to occur. Changing it to start at `nground` has fixed the issue. 

My apologies for the inconvenience with this and thank you again for your time.

**Comment by nikolasibalic** [comment] 2021-03-29 08:59
Great, thank you for resolving this issue.

I will add in the future some fence in the code to prevent addition of non-physical states when lower n range is not specified correctly. This should prevent and notify user in the future of similar mistakes.

**Closed** 2021-03-31 09:23 UTC
