### ISSUE TITLE
getStateLifetime F-states collapses jupyter

### ISSUE THREAD

**Issue by ranfinkelstein** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#41] opened 2020-03-23 12:40 UTC
Hi,
I am trying to run ```atom.getStateLifetime(28,3,3.5)```, with ```atom=Rubidium87()```. This causes jupyter lab to get stuck and collapse every time. If I try the same by with a D state (28,2,2.5) it works fine.
Is it because this is an F state? Are there any literature values for F states?
Any tips in general on how not to collapse Python? this seems to happen every time I run a heavy or an unorthodox calculation

**Comment by nikolasibalic** [comment] 2020-03-23 12:54
Hi @ranfinkelstein . I tried running
```python
from arc import *
atom=Rubidium87()
atom.getStateLifetime(28,3,3.5)
```
and I get
```1.5111533894283968e-05```

It might be that you hit bug described recently (#39 ), which messed up your local cache, or you interrupted calculation in some unfortunate way, which messed up cache too. So I would try to do following two things:

1. make sure installation updated by running ```pip install ARC-Alkali-Rydberg-Calculator --upgrade --no-cache-dir```
2. then clear local cache directory which is hidden directory in your home folder under name ```.arc-data``` . You can just delete that folder, and next time when you import arc fresh cache will be created.

If this doesn't solve your problem please let me know which OS and Python version you use, and do you run Python from some environment (like Spyder) or just plain command line or Jupyter notebook. If it does solve problem, let me know then too.  

If any other problems persist, please provide some code example, and I can give advice, or, in case it's some bug, provide fix.

**Comment by ranfinkelstein** [comment] 2020-03-24 08:30
Hi @nikolasibalic , thanks a lot for the prompt response.
I've uninstalled and reinstalled ARC and deleted the .arc-data folder, but still this command collapses python, although for different Rydberg states it works fine.
I have also reinstalled Python.
I am working in Win7, Python 3.8 (32-bit, maybe should install 64-bit like my OS), and running these commands either through Jupyter lab or through the command window.
It could be that I need to reinstall again everything from scratch.

**Comment by nikolasibalic** [comment] 2020-03-24 09:54
Hi @ranfinkelstein 

**Explanation:** The problem occurs because latest release of Python 3.8 was not yet supported by package. Whenever new Python is released for Windows it requires manual addition in the build system on my side 7c6909bb4da60763a472c15e01362a03cde7c620, and I was bit late with that as Python 3.8 is still fresh. Sorry for this. That explains behaviour you described:  you were able to run calculations whenever used dipole matrix elements were reused from cache, but the program was crashing whenever it tried to call dipole matrix element calculation for new state combinations, because that part was missing from package for your version of Python. 

**Solution:** You do not need to reinstall Python on your side. I have just released added packages for both 32 and 64bit Python 3.8 under Windows that you can get with

``` pip install ARC-Alkali-Rydberg-Calculator --upgrade --no-cache-dir```

**It should work then with your current version of Python.** Let me know.

If not, I would recommend installing Python from Anaconda distribution, that is [available here](https://www.anaconda.com/distribution/). Latest version there is Python 3.7 currently. That should work bit better and faster since that bundle is optimised for scientific calculations (it uses good backend libraries for numerics). And I would recommend using 64-bit version if you are on 64-bit machine. After removing installation of old Python 3.8, installation of Anaconda distribution of Python 3.7, you need just to run above mentioned command to get ARC to get for Python 3.7.

If even that doesn't work, please tell me! :)

**Comment by nikolasibalic** [comment] 2020-03-27 16:01
Hi @ranfinkelstein , I just want to check if the problem is solved (if I can close this issue now)?

**Comment by ranfinkelstein** [comment] 2020-03-28 09:29
Hi @nikolasibalic ,
I am in the process of resinstalling Python, but haven't tested this yet. 
I think you can close the issue and if something still goes wrong I'll let you know.

Thanks again
Ran

**Closed** 2020-03-30 21:20 UTC
Labels: improvement, question
